micro:
  component:
    elasticsearch:
      host: scrm-bus-es
      port: 9200
      port1: 9201
      port2: 9202
      cluster_name: scrm-es
      user_name:
      password:
      cluster:
        nodes: scrm-es.in-s01-bom04.elasticsearch.oppo.local:19527
